name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - projeto: projeto-api
            tipo: api
            cron_enabled: false

          - projeto: projeto-job
            tipo: cronjob
            cron_enabled: true

    steps:
      - uses: actions/checkout@v4

      - name: Mostrar projeto
        run: |
          echo "Projeto: ${{ matrix.projeto }}"
          echo "Tipo: ${{ matrix.tipo }}"

      - name: Desativar cron para API
        if: matrix.cron_enabled == false
        run: |
          sed -i 's|^\(\*/5 \* \* \* \* php artisan schedule:run\)|# \1|' crontab/crontab_prod

      - name: Ativar cron para Job
        if: matrix.cron_enabled == true
        run: |
          sed -i 's|^# \(.*php artisan schedule:run.*\)|\1|' crontab/crontab_prod

      - name: Mostrar crontab final
        run: cat crontab/crontab_prod

      - name: Build docker
        run: |
          docker build -t ${{ matrix.projeto }} .

      - name: Deploy
        run: |
          echo "Deploy do projeto ${{ matrix.projeto }}"
